import test from 'node:test';
import assert from 'node:assert/strict';
import snapshot from '../data/snapshot.json' with {type:'json'};
import {uniqueMatches,weeklyAward,playerRates,validDay,amsterdamDay,matchTotals} from '../lib/club-model.mjs';
import {ClubStore} from '../lib/club-store.ts';
class MemoryStorage{
 constructor(){this.values=new Map()}
 async get(key){return structuredClone(this.values.get(key))}
 async put(key,value){if(typeof key==='object'){for(const [k,v]of Object.entries(key))this.values.set(k,structuredClone(v))}else this.values.set(key,structuredClone(value))}
 async delete(key){return this.values.delete(key)}
 async list({prefix}){return new Map([...this.values].filter(([key])=>key.startsWith(prefix)).map(([k,v])=>[k,structuredClone(v)]))}
 async transaction(callback){return callback(this)}
}
const state=()=>{const storage=new MemoryStorage();return {storage,blockConcurrencyWhile:fn=>fn()}};
const json=async(store,url,options)=>{const r=await store.fetch(new Request('https://club.test'+url,options));return {status:r.status,data:await r.json()}};
function mockEA(newMatches=snapshot.matches){return async()=>Response.json({...snapshot,matches:newMatches,fetchedAt:new Date().toISOString()})}
test('archive de-duplicates match IDs and orders newest first',()=>{const m=uniqueMatches([...snapshot.matches,...snapshot.matches]);assert.equal(m.length,10);assert.ok(m.every((row,i)=>!i||m[i-1].timestamp>=row.timestamp));assert.equal(matchTotals(m).games,10)});
test('player comparison uses appearance rates rather than totals',()=>{const p=playerRates({gamesPlayed:'20',goals:'10',assists:'5',ratingAve:'7.2',passSuccessRate:'80',tacklesMade:'30'});assert.equal(p.goals,.5);assert.equal(p.assists,.25);assert.equal(p.tackles,1.5);assert.equal(playerRates({gamesPlayed:'0'}).goals,0)});
test('award excludes insufficient appearances and uses a rolling seven day window',()=>{const now=Date.parse('2026-10-07T12:00:00Z');const m=structuredClone(snapshot.matches[0]);const list=[0,1,2].map(i=>({...m,matchId:String(123000+i),timestamp:now/1000-i*86400,players:{'79638':{a:{playername:'Three games',rating:'8.0',goals:'1',assists:'0',mom:'0'},...(i===0?{b:{playername:'One game',rating:'10.0'}}:{})}}}));assert.equal(weeklyAward(list,now).name,'Three games');assert.equal(weeklyAward(list.slice(0,2),now),null);assert.equal(weeklyAward(list,now+10*86400000),null)});
test('archive survives a store restart and EA failure does not erase matches',async()=>{const previous=globalThis.fetch;try{const s=state();const store=new ClubStore(s);await store.ready;globalThis.fetch=mockEA();await store.sync();const extra=structuredClone(snapshot.matches[0]);extra.matchId='999999111';globalThis.fetch=mockEA([extra]);await store.sync();const restarted=new ClubStore(s);const before=await json(restarted,'/api/archive');assert.equal(before.data.matches.length,11);globalThis.fetch=async()=>{throw Error('Unavailable')};const failed=await restarted.sync();assert.equal(failed.mode,'snapshot');assert.match(failed.notice,/Otomatik/);const after=await json(restarted,'/api/archive');assert.equal(after.data.matches.length,11);assert.ok(after.data.notice)}finally{globalThis.fetch=previous}});
test('attendance updates are shared, replace existing status and survive restart',async()=>{const s=state();const store=new ClubStore(s);const day=amsterdamDay();const player=snapshot.members[0].name;const post=status=>json(store,'/api/attendance?date='+day,{method:'POST',body:JSON.stringify({player,status})});assert.equal((await post('yes')).status,200);assert.equal((await post('maybe')).data.entries.length,1);const r=await json(new ClubStore(s),'/api/attendance?date='+day);assert.equal(r.data.entries[0].status,'maybe');assert.equal(r.data.persistent,true)});
test('attendance rejects invalid players, status and dates',async()=>{const store=new ClubStore(state());const day=amsterdamDay();const post=body=>json(store,'/api/attendance?date='+day,{method:'POST',body:JSON.stringify(body)});assert.equal((await post({player:'unknown',status:'yes'})).status,400);assert.equal((await post({player:snapshot.members[0].name,status:'fake'})).status,400);assert.equal((await json(store,'/api/attendance?date=2026-02-31')).status,400);assert.equal(validDay('invalid'),false)});
test('feed HTTP failures preserve data, and a valid scheduled update clears errors',async()=>{const previous=globalThis.fetch;try{const store=new ClubStore(state());await store.ready;globalThis.fetch=async()=>new Response('Forbidden',{status:403});const failed=await store.sync();assert.equal(failed.syncFailure.code,'FEED_HTTP_403');assert.match(failed.notice,/Otomatik/);assert.equal(failed.matches.length,10);const cached=await json(store,'/api/club');assert.equal(cached.data.syncFailure.code,'FEED_HTTP_403');globalThis.fetch=mockEA();const recovered=await store.sync();assert.equal(recovered.mode,'scheduled');assert.equal((await json(store,'/api/club')).data.syncFailure,undefined)}finally{globalThis.fetch=previous}});

test('page reads never fetch upstream data; invalid feeds cannot erase stored records',async()=>{const previous=globalThis.fetch;try{const store=new ClubStore(state());await store.ready;let requests=0;globalThis.fetch=async()=>{requests++;return Response.json({...snapshot,club:{clubId:'999'}})};await json(store,'/api/club');assert.equal(requests,0);const failed=await store.sync();assert.equal(failed.syncFailure.code,'FEED_INVALID_DATA');assert.equal(failed.club.clubId,snapshot.club.clubId);assert.equal(failed.matches.length,10)}finally{globalThis.fetch=previous}});
