'use client';
import {useEffect,useMemo,useState,useSyncExternalStore} from 'react';
import {Activity,BarChart3,ArrowUpRight,CalendarDays,Check,ChevronRight,Clock,GitCompareArrows,Search,Shield,Trophy,Users,X} from 'lucide-react';
import PlayerAvatar from './player-avatar';
import TeamLab from './team-lab';
import WeeklyHighlights from './weekly-highlights';
import EventAnalysis from './event-analysis';
import AnalyticsDashboard, {AnalyticsComparison, AnalyticsPlayerDevelopment, NightPerformance} from './analytics-dashboard';
import MatchReport from './analytics-report';
import {LocationProvider, useLocationSearch, setLocationTab} from './analytics-location';
import {sectionPaths} from '../lib/club-routes';
import PlayerComparison from './player-comparison';
import MatchComparison from './match-comparison';
import snapshot from '../data/snapshot.json';
import {amsterdamDay,clubMatch,matchTotals,periodMatches,uniqueMatches} from '../lib/club-model.mjs';
import type { AwardSnapshot } from '../lib/derived-awards';
import type {Player,Match,MatchPlayer,ClubData} from '../lib/club-types';
type Archive={awardNotice?:string;awards?:AwardSnapshot[];matches:Match[];persistent:boolean;startedAt?:string;lastSync?:string;lastMatchUpdate?:string;notice?:string};
type Entry={player:string;status:'yes'|'maybe'|'no';updatedAt:string};
const positions:Record<string,string>={forward:'Forvet',midfielder:'Orta saha',defender:'Defans',goalkeeper:'Kaleci'};
const tabs=[['Genel bakış',Activity],['Maçlar',Trophy],['Analiz',BarChart3],['Takım Laboratuvarı',Activity],['Rövanş defteri',Trophy],['Kadro',Users],['Karşılaştır',GitCompareArrows],['Maç gecesi',CalendarDays]] as const;
const stamp=(value:string|number)=>new Date(typeof value==='number'?value*1000:value).toLocaleString('tr-TR',{timeZone:'Europe/Amsterdam',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const dateOnly=(value:number)=>new Date(value*1000).toLocaleDateString('tr-TR',{timeZone:'Europe/Amsterdam',day:'2-digit',month:'short'});
const fixed=(value:number,n=2)=>Number.isFinite(value)?value.toFixed(n):'—';
async function request<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,options);const data:unknown=await r.json();if(!r.ok){const error=data!==null&&typeof data==='object'&&'error' in data?data.error:undefined;throw Error(String(error||'İşlem tamamlanamadı.'));}return data as T;}
function subscribeHydration(){return()=>{}}
function readPlayerName(){try{return localStorage.getItem('leo-xi-player')||''}catch{return ''}}
function attendanceDateBounds(){const now=Date.now();return {min:amsterdamDay(now),max:amsterdamDay(now+31*86400000)}}
export default function Home({initialSearch=''}:{initialSearch?:string}){
 return <LocationProvider initialSearch={initialSearch}><Clubhouse/></LocationProvider>;
}
function Clubhouse(){
 const [localTab,setLocalTab]=useState('Genel bakış');
 const locationSearch=useLocationSearch();
 const locationTab=new URLSearchParams(locationSearch).get('leo_tab');
 const tab=tabs.some(([name])=>name===locationTab)?locationTab!:localTab;
 function setTab(name:string){setLocalTab(name);setLocationTab(name);window.scrollTo({top:0,behavior:'instant'})}
 // Preserve the server's source badge while initializing client requests as pending.
 const hasHydrated=useSyncExternalStore(subscribeHydration,()=>true,()=>false);
 const [data,setData]=useState<ClubData>(snapshot);const [busy,setBusy]=useState(true);const [notice,setNotice]=useState('');
 const [archive,setArchive]=useState<Archive>({matches:[],persistent:false});const [archiveError,setArchiveError]=useState('');
 const [period,setPeriod]=useState('all');const [resultFilter,setResultFilter]=useState('all');const [query,setQuery]=useState('');const [sort,setSort]=useState('goals');
 const [player,setPlayer]=useState<Player|null>(null);const [match,setMatch]=useState<Match|null>(null);
 const [a,setA]=useState(snapshot.members[0].name);const [b,setB]=useState(snapshot.members[1].name);
 const [day,setDay]=useState(()=>amsterdamDay());const [attendance,setAttendance]=useState<Entry[]>([]);const [attendanceError,setAttendanceError]=useState('');const [attendanceLoading,setAttendanceLoading]=useState(true);const [attendanceReady,setAttendanceReady]=useState(false);const [myName,setMyName]=useState(readPlayerName);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState('');
 const [dateBounds,setDateBounds]=useState(attendanceDateBounds);
 useEffect(()=>{
  async function loadArchive(){try{const value=await request<Archive>('/api/archive');setArchive(value);setArchiveError('');}catch(e){setArchiveError((e as Error).message)}}
  async function loadData(){try{const next=await request<ClubData>('/api/club');setData(next);setNotice(next.notice||'');await loadArchive();}catch(e){setNotice((e as Error).message+' Son kayıt gösteriliyor.');}finally{setBusy(false)}}
  void loadData();
  const timer=setInterval(()=>{setBusy(true);setNotice('');void loadData()},300000);
  return()=>clearInterval(timer);
 },[]);
 useEffect(()=>{let active=true;request<{entries:Entry[]}>('/api/attendance?date='+day).then(value=>{if(active){setAttendance(value.entries);setAttendanceReady(true)}}).catch(e=>{if(active)setAttendanceError(e.message)}).finally(()=>{if(active)setAttendanceLoading(false)});return()=>{active=false}},[day]);
 useEffect(()=>{const timer=setInterval(()=>{const next=attendanceDateBounds();setDateBounds(current=>current.min===next.min&&current.max===next.max?current:next)},60000);return()=>clearInterval(timer)},[]);
 function selectDay(next:string){if(!next||next===day)return;setDay(next);setAttendanceLoading(true);setAttendanceReady(false);setAttendanceError('');setAttendance([]);setSaved('')}
 useEffect(()=>{if(!player&&!match)return;const previousFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;const old=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPlayer(null);setMatch(null)}if(e.key==='Tab'){const controls=document.querySelectorAll<HTMLElement>('.modal button, .modal a, .modal select, .modal input, .modal [tabindex="0"]');const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',close);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',close);previousFocus?.focus()}},[player,match]);
 const allMatches=useMemo(()=>uniqueMatches([...archive.matches,...data.matches]) as Match[],[archive.matches,data.matches]);
 const filtered=periodMatches(allMatches,period).filter((m:Match)=>resultFilter==='all'||clubMatch(m)?.result===resultFilter) as Match[];
 const recent=allMatches.slice(0,10);const recentTotals=matchTotals(recent);
 const players=[...data.members].filter(p=>(p.name+' '+p.proName).toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))).sort((x,y)=>Number(y[sort as keyof Player])-Number(x[sort as keyof Player]));
 const o=data.overall;const top=[...data.members].sort((x,y)=>Number(y.goals)-Number(x.goals))[0];const assist=[...data.members].sort((x,y)=>Number(y.assists)-Number(x.assists))[0];
 const left=data.members.find(p=>p.name===a)||data.members[0];const right=data.members.find(p=>p.name===b)||data.members[1]||data.members[0];
 async function saveAttendance(status:Entry['status']){if(!myName)return;setSaving(true);setSaved('');setAttendanceError('');const selectedDay=day;try{const response=await request<{entries:Entry[]}>('/api/attendance?date='+selectedDay,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player:myName,status})});setAttendance(response.entries);setSaved('Katılımın kaydedildi.');try{localStorage.setItem('leo-xi-player',myName)}catch{}}catch(e){setAttendanceError((e as Error).message)}finally{setSaving(false)}}
 function openArchivedMatch(id:string){const raw=(archive.persistent?archive.matches:allMatches).find(m=>String(m.matchId)===id);if(raw){setPlayer(null);setMatch(raw)}}
 function matchRows(matches:Match[]){return matches.map(m=>{const c=clubMatch(m)!;return <button className="matchRow" key={m.matchId} onClick={()=>setMatch(m)} aria-label={`${c.opponent.details?.name} maçının detayları`}><span className={'result '+c.result}>{c.result}</span><span className="matchNames"><strong>LEO XI <span>vs</span> {c.opponent.details?.name||'Rakip'}</strong><small>{stamp(m.timestamp)} · Lig maçı</small></span><strong className="score">{c.goals}<span>:</span>{c.conceded}</strong><ChevronRight size={16}/></button>})}
 function playerCard(p:Player){return <div className="compareIdentity"><PlayerAvatar player={p}/><h3>{p.proName}</h3><p>{p.name} · {positions[p.favoritePosition]}</p><span className="miniTag">{p.gamesPlayed} maç</span></div>}
 return <div className="shell"><a className="skipLink" href="#main-content">İçeriğe geç</a><header className="siteHeader"><a className="brand" href={sectionPaths['Genel bakış']} onClick={e=>{e.preventDefault();setTab('Genel bakış')}}><img src="/leo-xi-logo.png" alt="LEO XI"/><span>LEO XI<small>CLUBHOUSE</small></span></a><div className="headerRight"><span className="sourceBadge"><i/>{busy&&hasHydrated?'Kayıt yükleniyor':'Kayıtlı EA verisi'}</span><span className="updateStamp">Takım / kadro kaydı<br/><strong>{stamp(data.fetchedAt)}</strong></span></div></header>
 <main id="main-content" tabIndex={-1} className={tab==='Genel bakış'?'':'detailPage'}>{notice&&<div className="notice" role="status">{notice}</div>}
 {tab==='Genel bakış'&&<section className="clubHero"><div className="heroCopy"><p className="eyebrow">EA SPORTS FC27 · PRO CLUBS</p><h1>Bir takım.<br/>Birlikte <span>daha ileri<span className="heroDot">.</span></span></h1><p className="heroSubtitle">Son maçlar, oyuncu performansı ve maç gecesi planı. Hepsi tek yerde.</p><div className="heroActions"><button className="primaryButton" onClick={()=>setTab('Maç gecesi')}>Maç gecesini planla <ArrowUpRight size={18}/></button><button className="textBtn" onClick={()=>setTab('Maçlar')}>Maçları keşfet <ChevronRight size={17}/></button></div><div className="clubMeta"><span><Shield size={14}/> Klasman {data.club.currentDivision}</span><span>SR {o.skillRating}</span><span>{data.members.length} oyuncu</span></div></div><div className="heroRecord"><div className="recordHeading"><span>01 / TAKIMIN FORMU</span><img src="/leo-xi-logo.png" alt="LEO XI aslan arması"/></div><h2>Aynı arma.<br/>Ortak hedef.</h2><p className="recordDescription">Kulüp toplamları ve son kayıtlı maçlar.</p><div className="recordStats"><div><strong>{o.wins}</strong><span>Galibiyet</span></div><div><strong>{o.ties}</strong><span>Beraberlik</span></div><div><strong>{o.losses}</strong><span>Mağlubiyet</span></div></div><div className="formGroup"><span>SON {recent.length} MAÇ</span><div>{recent.map(m=><span key={m.matchId} className={'formBadge '+clubMatch(m)!.result} title={`${dateOnly(m.timestamp)} · ${clubMatch(m)!.result}`}>{clubMatch(m)!.result}</span>)}</div></div><p className="recordFooter">Her maçtan öğren. Birlikte geliş.</p></div></section>}
 <nav className="tabs" aria-label="Kulüp bölümleri">{tabs.map(([name,Icon])=><a key={name} href={sectionPaths[name]} className={tab===name?'active':''} onClick={e=>{if(e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();setTab(name)}}} aria-current={tab===name?'page':undefined}><Icon size={18}/><span>{name}</span></a>)}</nav>
 {tab==='Genel bakış'&&<><div className="pageHead"><div><p className="eyebrow">TAKIMIN NABZI</p><h2>Takım özeti</h2></div><span className="miniTag">Kulüp toplamları</span></div><div className="statGrid">{[['Oynanan maç',o.gamesPlayed,'EA toplam kaydı'],['Galibiyet oranı',`%${Math.round(Number(o.wins)/Math.max(1,Number(o.gamesPlayed))*100)}`,`${o.wins} galibiyet`],['Atılan gol',o.goals,`${fixed(Number(o.goals)/Math.max(1,Number(o.gamesPlayed)))} / maç`],['Gol farkı',`${Number(o.goals)-Number(o.goalsAgainst)>0?'+':''}${Number(o.goals)-Number(o.goalsAgainst)}`,`${o.goalsAgainst} yenilen gol`]].map(([label,value,sub])=><article className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>)}</div>
 <WeeklyHighlights matches={archive.persistent?archive.matches:allMatches} members={data.members} onPlayer={setPlayer} onMatch={openArchivedMatch} asOf={archive.lastMatchUpdate||data.fetchedAt} rosterAsOf={data.fetchedAt}/>
 <section className="panel trendPanel"><div className="sectionHead"><div><p className="eyebrow">SON {recent.length} KAYITLI MAÇ</p><h3>Hücum & savunma</h3></div><span className="miniTag">{recentTotals.goals} : {recentTotals.conceded}</span></div><GoalChart matches={recent}/><div className="chartLegend"><span><i/>Atılan gol</span><span><i/>Yenilen gol</span></div><p className="footnote">Eskiden yeniye. Yalnız kayıtlı maçları içerir.</p></section>
 <div className="overviewGrid"><section className="panel"><div className="sectionHead"><div><p className="eyebrow">SON DÜDÜKTEN SONRA</p><h3>Son maçlar</h3></div><button className="textBtn" onClick={()=>setTab('Maçlar')}>Arşivi aç <ArrowUpRight size={16}/></button></div>{matchRows(recent.slice(0,4))}</section><section className="panel"><div className="sectionHead"><div><p className="eyebrow">KULÜP TOPLAMLARI</p><h3>Takım liderleri</h3></div><Users size={20}/></div>{([['Gol lideri',top,'goals'],['Asist lideri',assist,'assists']] as const).map(([label,p,metric])=><button className="leader" key={label} onClick={()=>setPlayer(p)}><PlayerAvatar player={p}/><span><small>{label}</small><strong>{p.proName}</strong><span>{p.name}</span></span><b>{p[metric]}</b><ChevronRight size={16}/></button>)}<button className="wideLink" onClick={()=>setTab('Karşılaştır')}>Oyuncuları karşılaştır <GitCompareArrows size={17}/></button></section></div></>}
 {tab==='Maçlar'&&<><div className="pageHead"><div><p className="eyebrow">KULÜBÜN HAFIZASI</p><h2>Maç arşivi</h2></div><span className="miniTag">{allMatches.length} kayıt</span></div><section className="panel"><div className="filterRow"><div className="segmented">{[['all','Tüm kayıtlar'],['week','Son 7 gün'],['month','Son 30 gün']].map(([value,label])=><button key={value} className={period===value?'chosen':''} onClick={()=>setPeriod(value)}>{label}</button>)}</div><select aria-label="Maç sonucu filtresi" value={resultFilter} onChange={e=>setResultFilter(e.target.value)}><option value="all">Tüm sonuçlar</option><option value="G">Galibiyet</option><option value="B">Beraberlik</option><option value="M">Mağlubiyet</option></select></div><ArchiveSummary matches={filtered}/>{matchRows(filtered)}{!filtered.length&&<p className="empty">Bu dönemde eşleşen kayıtlı maç bulunmuyor.</p>}<details className="archiveStatus"><summary>Veri güncelliği ve arşiv kapsamı</summary><span className={archive.persistent?'greenText':''}>{archive.persistent?'Kalıcı arşiv aktif':'Arşiv bağlantısı bekleniyor'}</span><p>{archiveError||'EA’nın son 10 lig maçı gece boyunca iki saatte bir, gece sonrasında dört kez alınmaya çalışılır. Başarılı alınan maçlar kalıcı arşive eklenir; önceki kayıtlar korunur. İki başarılı kayıt arasında 10’dan fazla maç oynanırsa daha önce alınmayan maçlar kaçabilir.'}</p>{archive.lastMatchUpdate&&<p>Son başarılı maç kaydı: {stamp(archive.lastMatchUpdate)}</p>}{archive.startedAt&&<small>Arşiv başlangıcı: {stamp(archive.startedAt)} · Önceden alınan 10 maç dahil. Bu kayıtlar tüm geçmiş sezonu temsil etmez.</small>}{archive.notice&&<p className="amberText">{archive.notice}</p>}</details></section></>}
 {tab==='Analiz'&&<><div className="pageHead"><div><p className="eyebrow">RAKAMLARIN ÖTESİNDE</p><h2>Performans analizi</h2></div><span className="miniTag">Kayıtlı maç analizi</span></div><AnalyticsDashboard members={data.members} asOf={archive.lastMatchUpdate||data.fetchedAt} rosterAsOf={data.fetchedAt} awards={archive.awards||[]} awardNotice={archive.awardNotice} matches={archive.persistent?archive.matches:allMatches} onMatch={id=>{const raw=(archive.persistent?archive.matches:allMatches).find(m=>String(m.matchId)===id);if(raw)setMatch(raw)}}/><details className="analyticsAdvanced noPrint"><summary>Ayrıntılı EA olay tablosu</summary><section className="panel"><div className="filterRow"><div className="segmented">{[['all','Tüm kayıtlar'],['week','Son 7 gün'],['month','Son 30 gün']].map(([value,label])=><button key={value} className={period===value?'chosen':''} onClick={()=>setPeriod(value)}>{label}</button>)}</div></div><EventAnalysis matches={periodMatches(allMatches,period)}/></section></details></>}
 {tab==='Kadro'&&<><div className="pageHead"><div><p className="eyebrow">AYNI ARMA ALTINDA</p><h2>Oyuncular</h2></div><span className="miniTag">{data.members.length} oyuncu</span></div><section className="panel"><div className="filterRow"><label className="search"><Search size={16}/><input aria-label="Oyuncu ara" placeholder="İsim veya kullanıcı adı…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Oyuncu sıralaması" value={sort} onChange={e=>setSort(e.target.value)}><option value="goals">Gol sıralaması</option><option value="assists">Asist sıralaması</option><option value="ratingAve">Ortalama puan</option><option value="gamesPlayed">Maç sayısı</option></select></div><div className="tableWrap"><table><thead><tr><th>#</th><th>OYUNCU</th><th>ROL</th><th>MAÇ</th><th>GOL</th><th>ASİST</th><th>ORT. PUAN</th><th>PAS %</th></tr></thead><tbody>{players.map((p,i)=><tr key={p.name}><td>{String(i+1).padStart(2,'0')}</td><td><button className="playerButton" onClick={()=>setPlayer(p)}><PlayerAvatar player={p} className="small"/><span><strong>{p.proName}</strong><small>{p.name}</small></span></button></td><td>{positions[p.favoritePosition]||p.favoritePosition}</td><td>{p.gamesPlayed}</td><td className="goldText">{p.goals}</td><td>{p.assists}</td><td><span className="rating">{p.ratingAve}</span></td><td>{p.passSuccessRate}%</td></tr>)}</tbody></table>{!players.length&&<p className="empty">Eşleşen oyuncu bulunamadı.</p>}</div><p className="mobileTableHint">Tüm istatistikleri görmek için tabloyu yana kaydır. Oyuncu adına dokunarak profilini aç.</p><p className="footnote">EA kulüp oyuncu istatistikleri. Maç arşivinin dönem filtresinden bağımsızdır.</p></section></>}
 {tab==='Karşılaştır'&&<><div className="pageHead"><div><p className="eyebrow">AYNI ÖLÇEKTE</p><h2>Oyuncu karşılaştırma</h2></div><span className="miniTag">Detaylı oyuncu verileri</span></div><section className="panel comparePanel"><div className="compareSelectors"><label>Birinci oyuncu<select value={left.name} onChange={e=>setA(e.target.value)}>{data.members.map(p=><option key={p.name} value={p.name}>{p.proName} · {p.name}</option>)}</select></label><span>vs</span><label>İkinci oyuncu<select value={right.name} onChange={e=>setB(e.target.value)}>{data.members.map(p=><option key={p.name} value={p.name}>{p.proName} · {p.name}</option>)}</select></label></div><div className="compareCards">{playerCard(left)}{playerCard(right)}</div>{left.name===right.name&&<p className="notice">Karşılaştırma için iki farklı oyuncu seçebilirsin.</p>}<PlayerComparison left={left} right={right} matches={allMatches}/><details className="analyticsAdvanced"><summary>Grafiklerle ayrıntılı karşılaştırma</summary><AnalyticsComparison matches={archive.persistent?archive.matches:allMatches} leftName={left.name} rightName={right.name} onMatch={openArchivedMatch}/></details></section></>}
 {tab==='Maç gecesi'&&<><div className="pageHead"><div><p className="eyebrow">BU AKŞAM KİM VAR?</p><h2>Maç gecesi</h2></div><CalendarDays size={25}/></div><div className="attendanceLayout"><section className="panel attendanceForm"><p className="eyebrow">KATILIMINI BİLDİR</p><h3>Planı birlikte yapalım.</h3><p className="bodyText">Günü ve kendi oyuncu adını seç. Katılım durumun tüm takımın ortak listesinde görünür.</p><label className="formLabel">Maç günü<input type="date" value={day} min={dateBounds.min} max={dateBounds.max} disabled={saving} onChange={e=>selectDay(e.target.value)}/></label><label className="formLabel">Oyuncu<select value={myName} disabled={saving} onChange={e=>{setMyName(e.target.value);setSaved('')}}><option value="">Kendi oyuncu adını seç</option>{data.members.map(p=><option key={p.name} value={p.name}>{p.proName} · {p.name}</option>)}</select></label><div className="attendanceActions">{([['yes','Geliyorum',Check],['maybe','Belki',Clock],['no','Gelemiyorum',X]] as const).map(([value,label,Icon])=><button key={value} disabled={!myName||saving||!attendanceReady} className={attendance.find(e=>e.player===myName)?.status===value?'selected '+value:value} onClick={()=>saveAttendance(value)}><Icon size={16}/>{label}</button>)}</div>{saving&&<p role="status" className="bodyText">Kaydediliyor…</p>}{saved&&<p role="status" className="greenText">{saved}</p>}{attendanceError&&<p role="alert" className="errorText">{attendanceError}</p>}<p className="footnote">Bu ortak katılım panosu oyuncu beyanıyla çalışır; EA&apos;dan gelen bir bilgi değildir.</p></section><section className="panel"><div className="sectionHead"><div><p className="eyebrow">{day.split('-').reverse().join('.')}</p><h3>Maç gecesi kadrosu</h3></div><span className="miniTag">{attendance.filter(e=>e.status==='yes').length} hazır</span></div>{attendanceLoading?<p className="empty">Katılım listesi yükleniyor…</p>:<>{[['yes','Geliyorum'],['maybe','Belki'],['no','Gelemiyorum']].map(([value,label])=><div className="attendanceGroup" key={value}><h4><i className={value}/>{label}<span>{attendance.filter(e=>e.status===value).length}</span></h4>{attendance.filter(e=>e.status===value).map(e=><div className="attendancePerson" key={e.player}><PlayerAvatar player={{name:e.player,proName:data.members.find(p=>p.name===e.player)?.proName||e.player}} className="small"/><div><strong>{data.members.find(p=>p.name===e.player)?.proName||e.player}</strong><small>{e.player}</small></div><small>{stamp(e.updatedAt)}</small></div>)}{!attendance.some(e=>e.status===value)&&<p className="quiet">Henüz kimse yok.</p>}</div>)}</>}{attendanceReady&&<p className="footnote">Katılım bildirmeyen: {data.members.filter(p=>!attendance.some(e=>e.player===p.name)).length} oyuncu.</p>}</section></div><NightPerformance key={day} matches={archive.persistent?archive.matches:allMatches} day={day} onMatch={openArchivedMatch}/></>}
 {tab==='Takım Laboratuvarı'&&<TeamLab matches={allMatches} onMatch={openArchivedMatch}/>}
 {tab==='Rövanş defteri'&&<TeamLab matches={allMatches} onMatch={openArchivedMatch} rematches/>}
 <footer><div><strong>LEO XI</strong><span>Bir takım. Tek ruh.</span></div><p>Kaynak: <a href="https://www.ea.com/games/ea-sports-fc/clubs/rankings" target="_blank" rel="noreferrer">EA Clubs ↗</a> · Takım/kadro: {stamp(data.fetchedAt)} · Maç arşivi: {stamp(archive.lastMatchUpdate||data.fetchedAt)} (Amsterdam)<br/>Bağımsız takım sitesi. EA SPORTS ile bağlantılı değildir.</p></footer></main>
 {(player||match)&&<div className={'modalBackdrop '+(player?'drawerBackdrop':'')} onClick={()=>{setPlayer(null);setMatch(null)}}><section className={'modal '+(match?'matchModal':'playerModal')} role="dialog" aria-modal="true" aria-label={match?'Maç detayları':'Oyuncu profili'} onClick={e=>e.stopPropagation()}><button autoFocus className="close" aria-label="Kapat" onClick={()=>{setPlayer(null);setMatch(null)}}><X/></button>{player&&<><p className="eyebrow">LEO XI / OYUNCU PROFİLİ</p><div className="profileIdentity"><PlayerAvatar player={player} className="profilePortrait"/><h2>{player.proName}</h2></div><p className="bodyText">{player.name} · {positions[player.favoritePosition]}</p><p className="profileSource">Kulüp toplamları · {stamp(data.fetchedAt)}</p><div className="profileStats">{[['Maç',player.gamesPlayed],['Gol',player.goals],['Asist',player.assists],['Ort. puan',player.ratingAve],['Maçın oyuncusu',player.manOfTheMatch],['Pas %',player.passSuccessRate]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><button className="primaryButton" onClick={()=>{setA(player.name);setPlayer(null);setTab('Karşılaştır')}}>Oyuncuyu karşılaştır <ArrowUpRight size={16}/></button><section className="playerMatchSection"><p className="eyebrow">KAYITLI MAÇLARDAN</p><h3>Oyununu yakından gör.</h3><p className="bodyText">Hücumdan savunmaya, {player.proName} için ayrıntılı maç verileri.</p><MatchComparison key={player.name} matches={allMatches} left={player} right={player} single/><AnalyticsPlayerDevelopment matches={archive.persistent?archive.matches:allMatches} name={player.name} onMatch={openArchivedMatch}/></section></>}{match&&<MatchDetails match={match} history={archive.persistent?archive.matches:allMatches} onMatch={id=>{const raw=(archive.persistent?archive.matches:allMatches).find(m=>String(m.matchId)===id);if(raw)setMatch(raw)}}/>}</section></div>}</div>;
}
function ArchiveSummary({matches}:{matches:Match[]}){const t=matchTotals(matches);return <div className="archiveTotals"><span><strong>{t.games}</strong> maç</span><span className="greenText"><strong>{t.wins}</strong> galibiyet</span><span className="goldText"><strong>{t.draws}</strong> beraberlik</span><span><strong>{t.losses}</strong> mağlubiyet</span><span><strong>{t.goals}:{t.conceded}</strong> goller</span></div>}
function GoalChart({matches}:{matches:Match[]}){const rows=[...matches].reverse();const max=Math.max(1,...rows.flatMap(m=>{const c=clubMatch(m)!;return [c.goals,c.conceded]}));const x=(i:number)=>45+(i/Math.max(1,rows.length-1))*470;const y=(n:number)=>160-(n/max)*120;const points=(metric:'goals'|'conceded')=>rows.map((m,i)=>`${x(i)},${y(clubMatch(m)![metric])}`).join(' ');return <svg className="goalChart" viewBox="0 0 560 195" role="img" aria-label={`Son ${rows.length} maçın atılan ve yenilen gol grafiği. Atılan ${matchTotals(rows).goals}, yenilen ${matchTotals(rows).conceded}.`}>{[0,.5,1].map(f=><g key={f}><line x1="45" x2="515" y1={y(max*f)} y2={y(max*f)} stroke="currentColor" opacity=".12"/><text x="20" y={y(max*f)+4} fill="currentColor" fontSize="10" opacity=".5">{fixed(max*f,(max*f)%1?1:0)}</text></g>)}<polyline points={points('goals')} stroke="var(--gold)" fill="none" strokeWidth="3" strokeLinejoin="round"/><polyline points={points('conceded')} stroke="var(--loss)" fill="none" strokeWidth="2" strokeDasharray="5 5"/>{rows.map((m,i)=><g key={m.matchId}><circle cx={x(i)} cy={y(clubMatch(m)!.goals)} r="4" fill="var(--gold)"><title>{`${dateOnly(m.timestamp)}: ${clubMatch(m)!.goals} atılan, ${clubMatch(m)!.conceded} yenilen gol`}</title></circle>{(i===0||i===rows.length-1||i===Math.floor(rows.length/2))&&<text x={x(i)} y="186" textAnchor="middle" fill="currentColor" opacity=".5" fontSize="10">{dateOnly(m.timestamp)}</text>}</g>)}</svg>}
function MatchDetails({match,history,onMatch}:{match:Match;history:Match[];onMatch:(id:string)=>void}){const c=clubMatch(match)!;const [team,setTeam]=useState('79638');const rows=(Object.entries(match.players?.[team]||{}) as [string,MatchPlayer][]).sort(([,a],[,b])=>Number(b.rating)-Number(a.rating));const opponentId=Object.keys(match.clubs).find(id=>id!=='79638')!;return <><p className="eyebrow">{stamp(match.timestamp)} · LİG MAÇI</p><div className="detailScore"><span>LEO XI</span><strong>{c.goals} : {c.conceded}</strong><span>{c.opponent.details?.name}</span></div><div className="segmented detailTeam"><button className={team==='79638'?'chosen':''} onClick={()=>setTeam('79638')}>LEO XI</button><button className={team===opponentId?'chosen':''} onClick={()=>setTeam(opponentId)}>Rakip kadro</button></div><div className="tableWrap"><table><thead><tr><th>OYUNCU</th><th>ROL</th><th>PUAN</th><th>GOL</th><th>ASİST</th><th>PAS</th><th>PAS %</th><th>MÜDAHALE</th></tr></thead><tbody>{rows.map(([id,p])=><tr key={id}><td><strong>{p.playername}</strong>{Number(p.mom)>0&&<span className="momTag">MVP</span>}</td><td>{positions[p.pos]||'—'}</td><td><span className="rating">{fixed(Number(p.rating),1)}</span></td><td>{p.goals??'—'}</td><td>{p.assists??'—'}</td><td>{p.passesmade??'—'} / {p.passattempts??'—'}</td><td>{Number(p.passattempts)>0?`${fixed(Number(p.passesmade)/Number(p.passattempts)*100,0)}%`:'—'}</td><td>{p.tacklesmade??'—'} / {p.tackleattempts??'—'}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">EA bu takımın oyuncu detaylarını döndürmedi.</p>}</div><details className="analyticsAdvanced"><summary>Ayrıntılı maç olayları</summary><EventAnalysis key={team} matches={[match]} teamId={team}/></details><p className="footnote">Pas ve müdahale: başarılı / deneme. EA maç kaydı; tam saha konumları gösterilmez.</p><MatchReport key={match.matchId} match={match} history={history} onMatch={onMatch}/></>}

