'use client';
import {useMemo,useState} from 'react';
import type {Match} from '../lib/club-types';
import type {ResearchContext,RatingSnapshot} from '../lib/research-types';
import {matchupRows,matchupReport,scenarioEstimate,prequentialValidation,roleOrder,roleNames,type Matchup,type Roster} from '../lib/opponent-lab';
const pct=(v:number|null)=>v===null?'—':`%${(v*100).toLocaleString('tr-TR',{maximumFractionDigits:1})}`;
const stamp=(v:string)=>new Date(v).toLocaleString('tr-TR',{timeZone:'Europe/Amsterdam',dateStyle:'short',timeStyle:'short'});
function RosterView({label,roster}:{label:string;roster:Roster}){return <div><h4>{label} · {roster.n||'—'} kayıtlı insan</h4><p>{roleOrder.map((r,i)=>`${roleNames[r]} ${roster.roles[i]}`).join(' · ')}{roster.unknown>0?` · Belirsiz ${roster.unknown}`:''}</p><ul>{roster.players.map(p=><li key={p.id}>{p.name} · {roleNames[p.role as keyof typeof roleNames]}</li>)}</ul></div>}
export function MatchupDetail({row}:{row:Matchup}){return <details className="matchupDetail"><summary>{row.opponent} · {row.gf}:{row.ga} · {row.own.n||'?'} × {row.other.n||'?'} insan</summary><p>Maç öncesi kayıtlı SR: LEO XI {row.ownSR??'bilinmiyor'} / rakip {row.otherSR??'bilinmiyor'}{row.dnf?' · DNF: karşılaştırma dışında':''}</p><div className="labColumns"><RosterView label="LEO XI" roster={row.own}/><RosterView label={row.opponent} roster={row.other}/></div></details>}
export default function OpponentLab({matches,ratings=[],research,onMatch}:{matches:Match[];ratings?:RatingSnapshot[];research?:ResearchContext;onMatch:(id:string)=>void}){
 const [matchType,setMatchType]=useState('all');
 const analysis=useMemo(()=>{const allRows=matchupRows(matches,ratings);const rows=allRows.filter(r=>matchType==='all'||r.type===matchType);return {rows,types:[...new Set(allRows.map(r=>r.type))],report:matchupReport(rows),validation:prequentialValidation(rows)};},[matches,ratings,matchType]);
 const {rows,report,validation}=analysis;
 const canPredict=validation.qualified&&new Set(rows.map(r=>r.type)).size===1;
 const [own,setOwn]=useState(8),[other,setOther]=useState(5),[useRoles,setUseRoles]=useState(false),[useSR,setUseSR]=useState(false),[gap,setGap]=useState(0);
 const [ownRoles,setOwnRoles]=useState([0,2,3,3]),[otherRoles,setOtherRoles]=useState([0,1,2,2]),[selected,setSelected]=useState('');
 const estimate=useMemo(()=>scenarioEstimate(rows,{own,other,...(useRoles?{ownRoles,otherRoles}:{}),...(useSR?{gap}:{})}),[rows,own,other,useRoles,ownRoles,otherRoles,useSR,gap]);
 const latest=new Map<string,RatingSnapshot>();for(const r of ratings)if(!latest.has(r.clubId)||r.observedAt>latest.get(r.clubId)!.observedAt)latest.set(r.clubId,r);
 const selectedGroup=report.counts.find(g=>g.label===selected),sample=selectedGroup?.games||rows;
 const observedOwn=[...new Set(report.valid.map(r=>r.own.n))].sort((a,b)=>a-b),observedOther=[...new Set(report.valid.map(r=>r.other.n))].sort((a,b)=>a-b);
 return <section className="opponentLab panel"><p className="eyebrow">RAKİP & KADRO LABORATUVARI</p><h3>Hangi eşleşmeler bize daha iyi geliyor?</h3><p>Kayıtlı insan sayısını, rol dağılımını ve maçtan önce alınmış Skill Rating farkını karşılaştır. Yeni maçlar arşive geldikçe analiz yenilenir.</p>
 <label className="formLabel">Maç türü<select value={matchType} onChange={e=>{setMatchType(e.target.value);setSelected('')}}><option value="all">Tüm kayıtlı türler</option>{analysis.types.map(t=><option key={t} value={t}>{t==='1'||t==='leagueMatch'?'Lig':t}</option>)}</select></label>
 <div className="matchupStats"><span><strong>{report.overall.n}</strong> geçerli maç</span><span><strong>{pct(report.overall.raw)}</strong> gözlenen galibiyet</span><span><strong>{rows.filter(r=>r.gap!==null).length}</strong> maçta geçmiş SR</span><span><strong>{report.excluded}</strong> DNF / eksik kadro dışlandı</span></div>
 <div className="labColumns"><div className="labOutcome"><h4>Gözlenen en yüksek oran</h4>{report.best?<p><strong>{report.best.label}</strong> · {pct(report.best.raw)} · {report.best.n} maç</p>:<p>En az 5 maç, 3 rakip ve 3 farklı maç günü olan grup bekleniyor.</p>}</div><div className="labOutcome"><h4>Gözlenen en düşük oran</h4>{report.worst?<p><strong>{report.worst.label}</strong> · {pct(report.worst.raw)} · {report.worst.n} maç</p>:<p>Karşılaştırılabilecek ikinci bir yeterli grup henüz yok.</p>}</div></div>
 <p className="footnote">Gruplar küçük örneklem düzeltmeli oranla sıralanır. “Daha çok insanla kazanırız” sonucu çıkarılamaz: rakip gücü, kadro kalitesi ve aynı geceki tekrarlar birlikte değişebilir. Aralıklar çakışıyorsa sıralama kesin değildir.</p>
 <h4>İnsan sayısı eşleşme haritası</h4><p className="footnote">Satır: biz · sütun: rakip. Hücre: gözlenen galibiyet oranı / maç sayısı. Hücreye basarak kaynak maçları süz.</p>
 <div className="tableWrap"><table className="matchupHeatmap"><thead><tr><th>Biz / Rakip</th>{observedOther.map(n=><th key={n}>{n} kişi</th>)}</tr></thead><tbody>{observedOwn.map(n=><tr key={n}><th>{n} kişi</th>{observedOther.map(o=>{const g=report.counts.find(x=>x.label===`${n} × ${o}`);return <td key={o}>{g?<button className={selected===g.label?'chosen':''} style={{background:`rgba(45,88,219,${.05+.3*g.smoothed})`}} aria-pressed={selected===g.label} onClick={()=>setSelected(selected===g.label?'':g.label)} aria-label={`${g.label}: ${g.w} galibiyet / ${g.n} maç`}><strong>{pct(g.raw)}</strong><small>{g.n} maç{!g.rankable?' · az veri':''}</small></button>:'—'}</td>})}</tr>)}</tbody></table></div>
 <div className="tableWrap"><table><thead><tr><th>Eşleşme</th><th>G / B / M</th><th>Düzeltilmiş G</th><th>%95 Wilson aralığı</th><th>Rakip / gün</th></tr></thead><tbody>{report.counts.map(g=><tr key={g.label}><td>{g.label}</td><td>{g.w} / {g.d} / {g.l}</td><td>{pct(g.smoothed)}</td><td>{pct(g.interval[0])}–{pct(g.interval[1])}</td><td>{g.uniqueOpponents} / {g.nights}</td></tr>)}</tbody></table></div>
 <div className="labColumns">{[{title:'Maç öncesi güç farkı',groups:report.strength},{title:'İnsanların rol dağılımı',groups:report.roles}].map(block=><section key={block.title}><h4>{block.title}</h4>{block.title.includes('rol')&&<p className="footnote">Kaleci–savunma–orta saha–hücum; biz / rakip. Bu sayılar 11 kişilik diziliş değildir.</p>}{block.groups.length?<div className="matchupBars">{block.groups.slice(0,12).map(g=><div key={g.label}><span>{g.label}</span><meter min={0} max={1} value={g.raw??0} aria-label={g.label+' galibiyet oranı'}/><small>{pct(g.raw)} · {g.n} maç · {g.n<5?'az veri':`${g.uniqueOpponents} rakip`}</small></div>)}</div>:<p>Geçerli tarihli veri birikmesi bekleniyor. Güncel SR geçmişe uygulanmaz.</p>}</section>)}</div>
 <section className="matchupScenario"><h4>Bir sonraki eşleşmeyi incele</h4><div className="labToolbar">{[{label:'Biz kaç kişiyiz?',value:own,set:setOwn},{label:'Rakip kaç kişi?',value:other,set:setOther}].map(x=><label key={x.label}>{x.label}<select value={x.value} onChange={e=>x.set(Number(e.target.value))}>{Array.from({length:11},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>)}<label><input type="checkbox" checked={useRoles} onChange={e=>setUseRoles(e.target.checked)}/> Rolleri karşılaştır</label><label><input type="checkbox" checked={useSR} onChange={e=>setUseSR(e.target.checked)}/> SR farkını kullan</label>{useSR&&<label>Bizim SR − rakip SR<input type="number" value={gap} onChange={e=>setGap(Number(e.target.value))}/></label>}</div>
 {useRoles&&<div className="labColumns">{[{title:'Bizim roller',values:ownRoles,set:setOwnRoles},{title:'Rakibin rolleri',values:otherRoles,set:setOtherRoles}].map(side=><fieldset key={side.title}><legend>{side.title}</legend><div className="labToolbar">{roleOrder.map((role,i)=><label key={role}>{roleNames[role]}<input type="number" min={0} max={role==='goalkeeper'?1:11} value={side.values[i]} onChange={e=>side.set(side.values.map((v,j)=>j===i?Number(e.target.value):v))}/></label>)}</div></fieldset>)}</div>}
 {estimate.error?<p role="alert">{estimate.error}</p>:<><p><strong>{estimate.enough&&canPredict&&!useRoles&&!useSR?'Doğrulanmış sayısal eşleşme tahmini':'Benzer kayıtların düzeltilmiş dağılımı'}</strong> · {estimate.stats.n} maç / {estimate.stats.uniqueOpponents} rakip / {estimate.stats.nights} gün</p>{estimate.stats.n>0?<><div className="matchupStats">{['Galibiyet','Beraberlik','Mağlubiyet'].map((s,i)=><span key={s}><strong>{pct(estimate.stats.probabilities[i])}</strong>{s}</span>)}</div><p>Gözlenen galibiyet: {pct(estimate.stats.raw)} · %95 aralık: {pct(estimate.stats.interval[0])}–{pct(estimate.stats.interval[1])}</p></>:<p>Bu eşleşmeye benzeyen kayıt yok; olasılık gösterilmiyor.</p>}{(!estimate.enough||!canPredict||useRoles||useSR)&&<p className="notice">Gelecek maç için doğrulanmış kazanma olasılığı değil. En az 20 benzer maç / 5 rakip / 5 gün ve geçmişten geleceğe tahmin kontrolü gerekiyor. Rol/SR ile süzülen dağılımlar betimleyicidir.</p>}</>}
 </section>
 <details><summary>Model denetimi ve kapsam</summary><p>Her sonuç için Dirichlet(1,1,1) başlangıcı: G=(galibiyet+1)/(maç+3). Wilson aralığı ham galibiyet oranının binom belirsizliğidir; günler arası bağımlılık nedeniyle gerçek belirsizlik daha büyük olabilir. Eşit insan sayısı; seçili roller için en fazla 1 oyuncunun rol farkı; SR için ±150 tolerans. DNF dışarıda. Eksik oyuncu listesi 0 kişi sayılmaz.</p><p>Kayıtlar insan oyuncu görünümleridir; EA listeyi eksik verirse gerçek insan sayısı doğrulanamaz. Pozisyonlar genel rol grubudur; CB/CDM/LW veya saha koordinatı tahmin edilmez.</p><p>Geçmişten geleceğe kontrol: {validation.n} uygun tahmin. Brier {validation.brier?.toFixed(3)??'—'} / basit geçmiş ortalaması {validation.baseline?.toFixed(3)??'—'} · kalibrasyon farkı {validation.calibration?.toFixed(3)??'—'}. Aynı gün ve sonraki maçlar eğitimden çıkarılır. Tahmin etiketi için ≥30 test, baz modelden düşük Brier ve ≤0,15 kalibrasyon farkı.</p></details>
 <details><summary>Rakiplerin son kaydedilen EA Skill Rating değerleri</summary><p className="footnote">EA Skill Rating, bizim hesapladığımız Elo değildir. Buradaki güncel puanlar geçmiş maçın puanı değildir.</p><div className="tableWrap"><table><thead><tr><th>Kulüp</th><th>SR</th><th>Gözlem tarihi</th></tr></thead><tbody>{[...latest.values()].map(r=><tr key={r.clubId}><td>{r.name}</td><td>{r.skillRating}</td><td>{stamp(r.observedAt)}</td></tr>)}</tbody></table></div>{!latest.size&&<p>İlk başarılı EA puan kaydı bekleniyor.</p>}</details>
 <details><summary>Maçlar ve iki tarafın oyuncuları ({sample.length}){selectedGroup?' · '+selected:''}</summary>{[...sample].reverse().map(row=><div key={row.id}><MatchupDetail row={row}/><button className="textBtn" onClick={()=>onMatch(row.id)}>Maç raporunu aç</button></div>)}</details>
 {research&&<details><summary>EA kaynak durumu · {stamp(research.observedAt)}</summary><ul>{research.endpoints.map(e=><li key={e.endpoint}>{e.endpoint}: {e.status==='ok'?'veri alındı':e.status==='empty'?'boş / beklenen şema yok':'yanıt alınamadı'}</li>)}</ul>{research.playoffs?.length?<p>Playoff kaydı: {research.playoffs.length} · şeması doğrulanmamış başarı kayıtları, oyuncu ödülü üretilmez.</p>:null}{research.info&&<p>Kulüp kimliği: {String(research.info.name||'LEO XI')} · #{String(research.info.clubId||'79638')}</p>}</details>}
 </section>;
}
