'use client';
import {useState} from 'react';
import {ArrowUpRight, RefreshCw, Trophy, Users, Activity, Shield, ChevronRight, Search, Target, ArrowDown, X} from 'lucide-react';
import snapshot from '../data/snapshot.json';
type Player=typeof snapshot.members[number]; type Match=typeof snapshot.matches[number];
const date=(s:string|number)=>new Date(typeof s==='number'?s*1000:s).toLocaleString('tr-TR',{timeZone:'Europe/Amsterdam',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const pos:Record<string,string>={forward:'Forvet',midfielder:'Orta saha',defender:'Defans',goalkeeper:'Kaleci'};
export default function Home(){
const [data,setData]=useState({...snapshot,notice:''});const [busy,setBusy]=useState(false);const [tab,setTab]=useState('Genel bakış');const [sort,setSort]=useState('goals');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Player|null>(null);const [filter,setFilter]=useState('Tümü');
async function refresh(){setBusy(true);try{const r=await fetch('/api/club');if(!r.ok)throw Error();setData(await r.json());}catch{setData(d=>({...d,notice:'Veri yenilenemedi. Son doğrulanmış kayıt gösteriliyor.'}));}finally{setBusy(false)}}
const o=data.overall;const players=[...data.members].filter(p=>(p.name+' '+p.proName).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b[sort as keyof Player])-Number(a[sort as keyof Player]));
const top=[...data.members].sort((a,b)=>Number(b.goals)-Number(a.goals))[0];const assist=[...data.members].sort((a,b)=>Number(b.assists)-Number(a.assists))[0];
function result(m:Match){const c=(m.clubs as any)['79638'];return Number(c.wins)?'G':Number(c.ties)?'B':'M'}
const matches=data.matches.filter(m=>filter==='Tümü'||result(m)===filter).sort((a,b)=>b.timestamp-a.timestamp);
return <div className="shell">
<div className="content"><div className="utilityBar"><span>LEO XI / PRO CLUBS</span><span>FC27 · Yeni nesil</span></div><header><a className="brand" href="#" onClick={()=>setTab('Genel bakış')}><img className="clubLogo" src="/leo-xi-logo.png" alt="LEO XI aslan arması"/><div>LEO XI <span>Club Tracker</span></div></a><div className="headerRight"><span className="status"><i/>{data.mode==='live'?'EA verisi yenilendi':'Doğrulanmış EA kaydı'}</span><button className="refresh" onClick={refresh} disabled={busy}><RefreshCw size={15} className={busy?'spin':''}/>{busy?'Yenileniyor':'Veriyi yenile'}</button></div></header>
<main>{data.notice&&<div className="notice" role="status">{data.notice}</div>}
<section className="clubSummary"><img className="summaryLogo" src="/leo-xi-logo.png" alt="LEO XI"/><div className="summaryIdentity"><div className="summaryTitle"><h1>LEO XI</h1><span className="clubBadge">FC27</span></div><div className="clubMeta"><span><Shield size={16}/> Klasman {data.club.currentDivision}</span><span>SR: {o.skillRating}</span><span>{data.members.length} oyuncu</span></div><div className="record"><strong className="winText">{o.wins} G</strong><strong className="drawText">{o.ties} B</strong><strong className="lossText">{o.losses} M</strong><span>{o.gamesPlayed} maç</span></div></div><img className="watermarkLogo" src="/leo-xi-logo.png" alt="" aria-hidden="true"/><div className="recentForm"><span>SON {data.matches.length} LİG MAÇI</span><div>{[...data.matches].sort((a,b)=>b.timestamp-a.timestamp).map(m=><span key={m.matchId} className={'formBadge '+result(m)} title={`${date(m.timestamp)} · ${result(m)==='G'?'Galibiyet':result(m)==='B'?'Beraberlik':'Mağlubiyet'}`}>{result(m)}</span>)}</div><small>En yeni maç solda · Kulüp ID: 79638</small></div></section>
<nav className="tabs" aria-label="Kulüp bölümleri">{[['Genel bakış',Activity],['Kadro',Users],['Maçlar',Trophy]].map(([name,Icon]:any)=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={18}/>{name}</button>)}</nav><div className="pagetitle"><div><p className="eyebrow">LEO XI / {tab.toUpperCase()}</p><h2>{tab==='Genel bakış'?'Performans özeti':tab==='Kadro'?'Oyuncu istatistikleri':'Maç geçmişi'}</h2></div><span className="season">EA CLUBS</span></div>
{tab==='Genel bakış'&&<>
<div className="statgrid">{[['Oynanan maç',o.gamesPlayed,'EA toplam maç kaydı'],['Galibiyet',o.wins,`${o.ties} beraberlik · ${o.losses} mağlubiyet`],['Atılan gol',o.goals,`${(Number(o.goals)/Number(o.gamesPlayed)).toFixed(2)} gol / maç`],['Galibiyet oranı',`%${Math.round(Number(o.wins)/Number(o.gamesPlayed)*100)}`,`${o.goalsAgainst} yenilen gol`]].map(([label,note,sub],i)=><article className="stat" key={label}><span>{label}<span className="statIcon">{i===2?<Target size={16}/>:<Activity size={16}/>}</span></span><strong>{note}</strong><small>{sub}</small></article>)}</div>
<div className="twocol"><section className="panel"><div className="sectionHead"><div><p className="eyebrow">SKOR TABLOSU</p><h3>Son maçlar</h3></div><button className="textBtn" onClick={()=>setTab('Maçlar')}>Tümünü gör <ArrowUpRight size={16}/></button></div>{matches.slice(0,4).map(m=>matchRow(m))}<p className="footnote">EA kaynağının döndürdüğü son lig maçları.</p></section><section className="panel leaders"><div className="sectionHead"><div><p className="eyebrow">ÖNE ÇIKANLAR</p><h3>Takımın itici gücü</h3></div><Trophy size={21}/></div>{[['Gol lideri',top,top.goals,'GOL'],['Asist lideri',assist,assist.assists,'ASİST']].map(([label,p,n,unit]:any)=><button className="leader" key={label} onClick={()=>setSelected(p)}><div className="avatar">{p.proName.slice(0,2).toUpperCase()}</div><div><small>{label}</small><strong>{p.proName}</strong><span>{p.name}</span></div><div className="leaderNum">{n}<small>{unit}</small></div></button>)}<div className="teamNote"><Shield size={22}/><p>Bireysel katkı.<br/><strong>Ortak başarı.</strong></p></div></section></div></>}
{(tab==='Genel bakış'||tab==='Kadro')&&<section className="panel squad"><div className="sectionHead"><div><p className="eyebrow">{data.members.length} OYUNCU · EA KADROSU</p><h3>Kadro & performans</h3></div><div className="controls"><label><Search size={16}/><input aria-label="Oyuncu ara" placeholder="Oyuncu ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Sıralama" value={sort} onChange={e=>setSort(e.target.value)}><option value="goals">Gol sıralaması</option><option value="assists">Asist sıralaması</option><option value="ratingAve">Ortalama puan</option><option value="gamesPlayed">Maç sayısı</option></select></div></div><div className="tableWrap"><table><thead><tr><th>#</th><th>OYUNCU</th><th>ROL</th><th>MAÇ</th><th>GOL <ArrowDown size={12}/></th><th>ASİST</th><th>ORT. PUAN</th><th>PAS %</th></tr></thead><tbody>{players.map((p,i)=><tr key={p.name} onClick={()=>setSelected(p)}><td>{String(i+1).padStart(2,'0')}</td><td><button className="playerBtn" onClick={()=>setSelected(p)}><span className="avatar small">{p.proName.slice(0,2).toUpperCase()}</span><span><strong>{p.proName}</strong><small>{p.name}</small></span></button></td><td>{pos[p.favoritePosition]||p.favoritePosition}</td><td>{p.gamesPlayed}</td><td className="gold">{p.goals}</td><td>{p.assists}</td><td><span className="rating">{p.ratingAve}</span></td><td>{p.passSuccessRate}%</td></tr>)}</tbody></table>{!players.length&&<p className="empty">Bu aramayla eşleşen oyuncu bulunamadı.</p>}</div></section>}
{tab==='Maçlar'&&<section className="panel"><div className="sectionHead"><div><p className="eyebrow">EA LİG MAÇLARI</p><h3>Maç merkezi</h3></div><div className="filters">{[['Tümü','Tümü'],['G','Galibiyet'],['B','Beraberlik'],['M','Mağlubiyet']].map(([v,l])=><button key={v} className={filter===v?'chosen':''} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>{matches.map(m=>matchRow(m))}{!matches.length&&<p className="empty">Bu filtreye uygun maç bulunmuyor.</p>}<p className="footnote">Bu liste tüm sezon arşivi değildir; EA kaynağının sunduğu son lig maçlarını gösterir.</p></section>}
<footer><div className="footerBrand">LEO XI <span>Birlikte oynuyoruz.</span></div><p>Kaynak: <a href="https://www.ea.com/games/ea-sports-fc/clubs/rankings" target="_blank" rel="noreferrer">EA Clubs ↗</a> · Kayıt: {date(data.fetchedAt)} (Amsterdam)<br/>Bağımsız takım sitesi. EA SPORTS ile bağlantılı değildir.</p></footer>
</main></div>{selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Oyuncu detayları" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Kapat" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">LEO XI / OYUNCU PROFİLİ</p><h2>{selected.proName}</h2><p>{selected.name} · {pos[selected.favoritePosition]}</p><div className="profileStats">{[['Maç',selected.gamesPlayed],['Gol',selected.goals],['Asist',selected.assists],['Ort. puan',selected.ratingAve],['Maçın oyuncusu',selected.manOfTheMatch],['Başarılı pas %',selected.passSuccessRate]].map(([l,v])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><button className="refresh" onClick={()=>setSelected(null)}>Kadroyа dön</button></section></div>}</div>;
function matchRow(m:Match){const clubs=m.clubs as any;const us=clubs['79638'];const rival=Object.entries(clubs).find(([id])=>id!=='79638')?.[1] as any;const r=result(m);return <article className="matchRow" key={m.matchId}><span className={'result '+r}>{r}</span><div className="matchNames"><strong>LEO XI <span>vs</span> {rival?.details?.name||'Rakip'}</strong><small>{date(m.timestamp)} · Lig maçı</small></div><strong className="score">{us.goals} <span>:</span> {rival?.goals??us.goalsAgainst}</strong></article>}
}
