'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,BarChart3,ArrowDown,ArrowUpRight,CalendarDays,Check,ChevronRight,Clock,GitCompareArrows,Search,Shield,Trophy,Users,X} from 'lucide-react';
import EventAnalysis from './event-analysis';
import PlayerComparison from './player-comparison';
import snapshot from '../data/snapshot.json';
import {amsterdamDay,clubMatch,matchTotals,periodMatches,uniqueMatches,weeklyAward} from '../lib/club-model.mjs';
type Player=typeof snapshot.members[number];
type Match={matchId:string;timestamp:number;clubs:Record<string,any>;players?:Record<string,Record<string,any>>};
type ClubData={club:any;overall:any;members:Player[];matches:Match[];fetchedAt:string;mode:string;notice?:string};
type Archive={matches:Match[];persistent:boolean;startedAt?:string;lastSync?:string;notice?:string};
type Entry={player:string;status:'yes'|'maybe'|'no';updatedAt:string};
const positions:Record<string,string>={forward:'Forvet',midfielder:'Orta saha',defender:'Defans',goalkeeper:'Kaleci'};
const tabs=[['Genel bakış',Activity],['Maçlar',Trophy],['Analiz',BarChart3],['Kadro',Users],['Karşılaştır',GitCompareArrows],['Maç gecesi',CalendarDays]] as const;
const stamp=(value:string|number)=>new Date(typeof value==='number'?value*1000:value).toLocaleString('tr-TR',{timeZone:'Europe/Amsterdam',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const dateOnly=(value:number)=>new Date(value*1000).toLocaleDateString('tr-TR',{timeZone:'Europe/Amsterdam',day:'2-digit',month:'short'});
const fixed=(value:number,n=2)=>Number.isFinite(value)?value.toFixed(n):'—';
async function request<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,options);const data:any=await r.json();if(!r.ok)throw Error(data.error||'İşlem tamamlanamadı.');return data;}
export default function Home(){
 const [data,setData]=useState<ClubData>(snapshot as unknown as ClubData);const [tab,setTab]=useState('Genel bakış');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const [archive,setArchive]=useState<Archive>({matches:[],persistent:false});const [archiveError,setArchiveError]=useState('');
 const [period,setPeriod]=useState('all');const [resultFilter,setResultFilter]=useState('all');const [query,setQuery]=useState('');const [sort,setSort]=useState('goals');
 const [player,setPlayer]=useState<Player|null>(null);const [match,setMatch]=useState<Match|null>(null);
 const [a,setA]=useState(snapshot.members[0].name);const [b,setB]=useState(snapshot.members[1].name);
 const [day,setDay]=useState(amsterdamDay());const [attendance,setAttendance]=useState<Entry[]>([]);const [attendanceError,setAttendanceError]=useState('');const [attendanceLoading,setAttendanceLoading]=useState(false);const [attendanceReady,setAttendanceReady]=useState(false);const [myName,setMyName]=useState('');const [saving,setSaving]=useState(false);const [saved,setSaved]=useState('');
 async function loadArchive(){try{const value=await request<Archive>('/api/archive');setArchive(value);setArchiveError('');}catch(e){setArchiveError((e as Error).message)}}
 async function loadData(){setBusy(true);setNotice('');try{const next=await request<ClubData>('/api/club');setData(next);setNotice(next.notice||'');await loadArchive();}catch(e){setNotice((e as Error).message+' Son kayıt gösteriliyor.');}finally{setBusy(false)}}
 useEffect(()=>{void loadData();const timer=setInterval(()=>void loadData(),300000);try{setMyName(localStorage.getItem('leo-xi-player')||'')}catch{}return()=>clearInterval(timer)},[]);
 useEffect(()=>{let active=true;setAttendanceLoading(true);setAttendanceReady(false);setAttendanceError('');setAttendance([]);setSaved('');request<{entries:Entry[]}>('/api/attendance?date='+day).then(value=>{if(active){setAttendance(value.entries);setAttendanceReady(true)}}).catch(e=>{if(active)setAttendanceError(e.message)}).finally(()=>{if(active)setAttendanceLoading(false)});return()=>{active=false}},[day]);
 useEffect(()=>{if(!player&&!match)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPlayer(null);setMatch(null)}if(e.key==='Tab'){const controls=document.querySelectorAll<HTMLElement>('.modal button, .modal a, .modal select, .modal input, .modal [tabindex="0"]');const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',close);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',close)}},[player,match]);
 const allMatches=useMemo(()=>uniqueMatches([...archive.matches,...data.matches]) as Match[],[archive.matches,data.matches]);
 const filtered=periodMatches(allMatches,period).filter((m:Match)=>resultFilter==='all'||clubMatch(m)?.result===resultFilter) as Match[];
 const recent=allMatches.slice(0,10);const recentTotals=matchTotals(recent);const award=weeklyAward(allMatches);
 const players=[...data.members].filter(p=>(p.name+' '+p.proName).toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))).sort((x,y)=>Number(y[sort as keyof Player])-Number(x[sort as keyof Player]));
 const o=data.overall;const top=[...data.members].sort((x,y)=>Number(y.goals)-Number(x.goals))[0];const assist=[...data.members].sort((x,y)=>Number(y.assists)-Number(x.assists))[0];
 const left=data.members.find(p=>p.name===a)||data.members[0];const right=data.members.find(p=>p.name===b)||data.members[1]||data.members[0];
 async function saveAttendance(status:Entry['status']){if(!myName)return;setSaving(true);setSaved('');setAttendanceError('');const selectedDay=day;try{const response=await request<{entries:Entry[]}>('/api/attendance?date='+selectedDay,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player:myName,status})});setAttendance(response.entries);setSaved('Katılımın kaydedildi.');try{localStorage.setItem('leo-xi-player',myName)}catch{}}catch(e){setAttendanceError((e as Error).message)}finally{setSaving(false)}}
 function matchRows(matches:Match[]){return matches.map(m=>{const c=clubMatch(m)!;return <button className="matchRow" key={m.matchId} onClick={()=>setMatch(m)} aria-label={`${c.opponent.details?.name} maçının detayları`}><span className={'result '+c.result}>{c.result}</span><span className="matchNames"><strong>LEO XI <span>vs</span> {c.opponent.details?.name||'Rakip'}</strong><small>{stamp(m.timestamp)} · Lig maçı</small></span><strong className="score">{c.goals}<span>:</span>{c.conceded}</strong><ChevronRight size={16}/></button>})}
 function playerCard(p:Player){return <div className="compareIdentity"><span className="avatar">{p.proName.slice(0,2).toUpperCase()}</span><h3>{p.proName}</h3><p>{p.name} · {positions[p.favoritePosition]}</p><span className="miniTag">{p.gamesPlayed} maç</span></div>}
 return <div className="shell"><header className="siteHeader"><a className="brand" href="#" onClick={()=>setTab('Genel bakış')}><img src="/leo-xi-logo.png" alt="LEO XI"/><span>LEO XI<small>CLUBHOUSE</small></span></a><div className="headerRight"><span className="sourceBadge"><i/>{busy?'Kayıt yükleniyor':'Kayıtlı EA verisi'}</span><span className="updateStamp">Son başarılı kayıt<br/><strong>{stamp(data.fetchedAt)}</strong></span></div></header>
 <main>{notice&&<div className="notice" role="status">{notice}</div>}
 <section className="clubHero"><div className="heroCopy"><p className="eyebrow">EA SPORTS FC27 · PRO CLUBS</p><h1>Tek arma.<br/><span>Tek takım.</span></h1><p className="heroSubtitle">Her maç bir hikâye. Bu, bizimki.</p><div className="clubMeta"><span><Shield size={14}/> Klasman {data.club.currentDivision}</span><span>SR {o.skillRating}</span><span>{data.members.length} oyuncu</span></div></div><img className="heroLogo" src="/leo-xi-logo.png" alt="LEO XI aslan arması"/><div className="heroRecord"><div><strong>{o.wins}</strong><span>Galibiyet</span></div><div><strong>{o.ties}</strong><span>Beraberlik</span></div><div><strong>{o.losses}</strong><span>Mağlubiyet</span></div><div className="formGroup"><span>SON {recent.length} MAÇ</span><div>{recent.map(m=><span key={m.matchId} className={'formBadge '+clubMatch(m)!.result} title={`${dateOnly(m.timestamp)} · ${clubMatch(m)!.result}`}>{clubMatch(m)!.result}</span>)}</div></div></div></section>
 <nav className="tabs" aria-label="Kulüp bölümleri">{tabs.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>{setTab(name);setNotice('')}} aria-current={tab===name?'page':undefined}><Icon size={18}/><span>{name}</span></button>)}</nav>
 {tab==='Genel bakış'&&<><div className="pageHead"><div><p className="eyebrow">TAKIMIN NABZI</p><h2>Oyun rakamlarda.</h2></div><span className="miniTag">Kulüp toplamları</span></div><div className="statGrid">{[['Oynanan maç',o.gamesPlayed,'EA toplam kaydı'],['Galibiyet oranı',`%${Math.round(Number(o.wins)/Math.max(1,Number(o.gamesPlayed))*100)}`,`${o.wins} galibiyet`],['Atılan gol',o.goals,`${fixed(Number(o.goals)/Math.max(1,Number(o.gamesPlayed)))} / maç`],['Gol farkı',`${Number(o.goals)-Number(o.goalsAgainst)>0?'+':''}${Number(o.goals)-Number(o.goalsAgainst)}`,`${o.goalsAgainst} yenilen gol`]].map(([label,value,sub])=><article className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>)}</div>
 <div className="overviewGrid"><section className="panel trendPanel"><div className="sectionHead"><div><p className="eyebrow">SON {recent.length} KAYITLI MAÇ</p><h3>Hücum & savunma</h3></div><span className="miniTag">{recentTotals.goals} : {recentTotals.conceded}</span></div><GoalChart matches={recent}/><div className="chartLegend"><span><i/>Atılan gol</span><span><i/>Yenilen gol</span></div><p className="footnote">Eskiden yeniye. Yalnız kayıtlı maçları içerir.</p></section><section className="panel award"><p className="eyebrow"><Trophy size={13}/> SON 7 GÜN</p><h3>Haftanın oyuncusu</h3>{award?<><div className="awardMonogram">{award.name.slice(0,2).toUpperCase()}</div><h4>{data.members.find(p=>p.name===award.name)?.proName||award.name}</h4><p>{award.name}</p><div className="awardStats"><div><strong>{fixed(award.average,2)}</strong><span>Ort. puan</span></div><div><strong>{award.games}</strong><span>Maç</span></div><div><strong>{award.goals+award.assists}</strong><span>Gol + asist</span></div></div></>:<div className="awardEmpty"><Trophy size={30}/><p>Henüz yeterli maç yok.</p><small>Son 7 günde en az 3 kayıtlı maç gerekir.</small></div>}<p className="footnote">En yüksek ortalama EA maç puanı. Eşitlikte maçın oyuncusu sayısı, sonra maç sayısı kullanılır. Yalnız arşivdeki maçlara göre.</p></section></div>
 <div className="overviewGrid"><section className="panel"><div className="sectionHead"><div><p className="eyebrow">SON DÜDÜKTEN SONRA</p><h3>Son maçlar</h3></div><button className="textBtn" onClick={()=>setTab('Maçlar')}>Arşivi aç <ArrowUpRight size={16}/></button></div>{matchRows(recent.slice(0,4))}</section><section className="panel"><div className="sectionHead"><div><p className="eyebrow">KULÜP TOPLAMLARI</p><h3>Fark yaratanlar</h3></div><Users size={20}/></div>{[['Gol lideri',top,'goals'],['Asist lideri',assist,'assists']].map(([label,p,metric]:any)=><button className="leader" key={label} onClick={()=>setPlayer(p)}><span className="avatar">{p.proName.slice(0,2).toUpperCase()}</span><span><small>{label}</small><strong>{p.proName}</strong><span>{p.name}</span></span><b>{p[metric]}</b><ChevronRight size={16}/></button>)}<button className="wideLink" onClick={()=>setTab('Karşılaştır')}>Oyuncuları karşılaştır <GitCompareArrows size={17}/></button></section></div></>}
 {tab==='Maçlar'&&<><div className="pageHead"><div><p className="eyebrow">KULÜBÜN HAFIZASI</p><h2>Her maç burada.</h2></div><span className="miniTag">{allMatches.length} kayıt</span></div><section className="panel"><div className="filterRow"><div className="segmented">{[['all','Tüm kayıtlar'],['week','Son 7 gün'],['month','Son 30 gün']].map(([value,label])=><button key={value} className={period===value?'chosen':''} onClick={()=>setPeriod(value)}>{label}</button>)}</div><select aria-label="Maç sonucu filtresi" value={resultFilter} onChange={e=>setResultFilter(e.target.value)}><option value="all">Tüm sonuçlar</option><option value="G">Galibiyet</option><option value="B">Beraberlik</option><option value="M">Mağlubiyet</option></select></div><ArchiveSummary matches={filtered}/>{matchRows(filtered)}{!filtered.length&&<p className="empty">Bu dönemde eşleşen kayıtlı maç bulunmuyor.</p>}<div className="archiveStatus"><span className={archive.persistent?'greenText':''}>{archive.persistent?'Kalıcı arşiv aktif':'Arşiv bağlantısı bekleniyor'}</span><p>{archiveError||'Her gün EA’nın son 10 lig maçını alma denemesi yapılır. Başarılı alınan maçlar kalıcı arşive eklenir; önceki kayıtlar korunur. Bir günde 10’dan fazla maç oynanırsa daha önce alınmayan maçlar kaçabilir.'}</p>{archive.startedAt&&<small>Arşiv başlangıcı: {stamp(archive.startedAt)} · Önceden alınan 10 maç dahil. Bu kayıtlar tüm geçmiş sezonu temsil etmez.</small>}{archive.notice&&<p className="amberText">{archive.notice}</p>}</div></section></>}
 {tab==='Analiz'&&<><div className="pageHead"><div><p className="eyebrow">RAKAMLARIN ÖTESİNDE</p><h2>Oyunu daha yakından gör.</h2></div><span className="miniTag">Kayıtlı maç analizi</span></div><section className="panel"><div className="filterRow"><div className="segmented">{[['all','Tüm kayıtlar'],['week','Son 7 gün'],['month','Son 30 gün']].map(([value,label])=><button key={value} className={period===value?'chosen':''} onClick={()=>setPeriod(value)}>{label}</button>)}</div></div><EventAnalysis matches={periodMatches(allMatches,period)}/></section></>}
 {tab==='Kadro'&&<><div className="pageHead"><div><p className="eyebrow">AYNI ARMA ALTINDA</p><h2>Bizim kadro.</h2></div><span className="miniTag">{data.members.length} oyuncu</span></div><section className="panel"><div className="filterRow"><label className="search"><Search size={16}/><input aria-label="Oyuncu ara" placeholder="İsim veya kullanıcı adı…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Oyuncu sıralaması" value={sort} onChange={e=>setSort(e.target.value)}><option value="goals">Gol sıralaması</option><option value="assists">Asist sıralaması</option><option value="ratingAve">Ortalama puan</option><option value="gamesPlayed">Maç sayısı</option></select></div><div className="tableWrap"><table><thead><tr><th>#</th><th>OYUNCU</th><th>ROL</th><th>MAÇ</th><th>GOL</th><th>ASİST</th><th>ORT. PUAN</th><th>PAS %</th></tr></thead><tbody>{players.map((p,i)=><tr key={p.name}><td>{String(i+1).padStart(2,'0')}</td><td><button className="playerButton" onClick={()=>setPlayer(p)}><span className="avatar small">{p.proName.slice(0,2).toUpperCase()}</span><span><strong>{p.proName}</strong><small>{p.name}</small></span></button></td><td>{positions[p.favoritePosition]||p.favoritePosition}</td><td>{p.gamesPlayed}</td><td className="goldText">{p.goals}</td><td>{p.assists}</td><td><span className="rating">{p.ratingAve}</span></td><td>{p.passSuccessRate}%</td></tr>)}</tbody></table>{!players.length&&<p className="empty">Eşleşen oyuncu bulunamadı.</p>}</div><p className="footnote">EA kulüp oyuncu istatistikleri. Maç arşivinin dönem filtresinden bağımsızdır.</p></section></>}
 {tab==='Karşılaştır'&&<><div className="pageHead"><div><p className="eyebrow">AYNI ÖLÇEKTE</p><h2>Katkıyı karşılaştır.</h2></div><span className="miniTag">Detaylı oyuncu verileri</span></div><section className="panel comparePanel"><div className="compareSelectors"><label>Birinci oyuncu<select value={left.name} onChange={e=>setA(e.target.value)}>{data.members.map(p=><option key={p.name} value={p.name}>{p.proName} · {p.name}</option>)}</select></label><span>vs</span><label>İkinci oyuncu<select value={right.name} onChange={e=>setB(e.target.value)}>{data.members.map(p=><option key={p.name} value={p.name}>{p.proName} · {p.name}</option>)}</select></label></div><div className="compareCards">{playerCard(left)}{playerCard(right)}</div>{left.name===right.name&&<p className="notice">Karşılaştırma için iki farklı oyuncu seçebilirsin.</p>}<PlayerComparison left={left} right={right} matches={allMatches}/></section></>}
 {tab==='Maç gecesi'&&<><div className="pageHead"><div><p className="eyebrow">BU AKŞAM KİM VAR?</p><h2>Birlikte sahaya.</h2></div><CalendarDays size={25}/></div><div className="attendanceLayout"><section className="panel attendanceForm"><p className="eyebrow">KATILIMINI BİLDİR</p><h3>Planı birlikte yapalım.</h3><p className="bodyText">Günü ve kendi oyuncu adını seç. Katılım durumun tüm takımın ortak listesinde görünür.</p><label className="formLabel">Maç günü<input type="date" value={day} min={amsterdamDay()} max={amsterdamDay(Date.now()+31*86400000)} disabled={saving} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/></label><label className="formLabel">Oyuncu<select value={myName} disabled={saving} onChange={e=>{setMyName(e.target.value);setSaved('')}}><option value="">Kendi oyuncu adını seç</option>{data.members.map(p=><option key={p.name} value={p.name}>{p.proName} · {p.name}</option>)}</select></label><div className="attendanceActions">{[['yes','Geliyorum',Check],['maybe','Belki',Clock],['no','Gelemiyorum',X]].map(([value,label,Icon]:any)=><button key={value} disabled={!myName||saving||!attendanceReady} className={attendance.find(e=>e.player===myName)?.status===value?'selected '+value:value} onClick={()=>saveAttendance(value)}><Icon size={16}/>{label}</button>)}</div>{saving&&<p role="status" className="bodyText">Kaydediliyor…</p>}{saved&&<p role="status" className="greenText">{saved}</p>}{attendanceError&&<p role="alert" className="errorText">{attendanceError}</p>}<p className="footnote">Bu ortak katılım panosu oyuncu beyanıyla çalışır; EA'dan gelen bir bilgi değildir.</p></section><section className="panel"><div className="sectionHead"><div><p className="eyebrow">{day.split('-').reverse().join('.')}</p><h3>Maç gecesi kadrosu</h3></div><span className="miniTag">{attendance.filter(e=>e.status==='yes').length} hazır</span></div>{attendanceLoading?<p className="empty">Katılım listesi yükleniyor…</p>:<>{[['yes','Geliyorum'],['maybe','Belki'],['no','Gelemiyorum']].map(([value,label])=><div className="attendanceGroup" key={value}><h4><i className={value}/>{label}<span>{attendance.filter(e=>e.status===value).length}</span></h4>{attendance.filter(e=>e.status===value).map(e=><div className="attendancePerson" key={e.player}><span className="avatar small">{(data.members.find(p=>p.name===e.player)?.proName||e.player).slice(0,2).toUpperCase()}</span><div><strong>{data.members.find(p=>p.name===e.player)?.proName||e.player}</strong><small>{e.player}</small></div><small>{stamp(e.updatedAt)}</small></div>)}{!attendance.some(e=>e.status===value)&&<p className="quiet">Henüz kimse yok.</p>}</div>)}</>}{attendanceReady&&<p className="footnote">Katılım bildirmeyen: {data.members.filter(p=>!attendance.some(e=>e.player===p.name)).length} oyuncu.</p>}</section></div></>}
 <footer><div><strong>LEO XI</strong><span>Bir takım. Tek ruh.</span></div><p>Kaynak: <a href="https://www.ea.com/games/ea-sports-fc/clubs/rankings" target="_blank" rel="noreferrer">EA Clubs ↗</a> · Kayıt: {stamp(data.fetchedAt)} (Amsterdam)<br/>Bağımsız takım sitesi. EA SPORTS ile bağlantılı değildir.</p></footer></main>
 {(player||match)&&<div className="modalBackdrop" onClick={()=>{setPlayer(null);setMatch(null)}}><section className={'modal '+(match?'matchModal':'')} role="dialog" aria-modal="true" aria-label={match?'Maç detayları':'Oyuncu profili'} onClick={e=>e.stopPropagation()}><button autoFocus className="close" aria-label="Kapat" onClick={()=>{setPlayer(null);setMatch(null)}}><X/></button>{player&&<><p className="eyebrow">LEO XI / OYUNCU PROFİLİ</p><h2>{player.proName}</h2><p className="bodyText">{player.name} · {positions[player.favoritePosition]}</p><div className="profileStats">{[['Maç',player.gamesPlayed],['Gol',player.goals],['Asist',player.assists],['Ort. puan',player.ratingAve],['Maçın oyuncusu',player.manOfTheMatch],['Pas %',player.passSuccessRate]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><button className="primaryButton" onClick={()=>{setA(player.name);setPlayer(null);setTab('Karşılaştır')}}>Oyuncuyu karşılaştır <ArrowUpRight size={16}/></button></>}{match&&<MatchDetails match={match}/>}</section></div>}</div>;
}
function ArchiveSummary({matches}:{matches:Match[]}){const t=matchTotals(matches);return <div className="archiveTotals"><span><strong>{t.games}</strong> maç</span><span className="greenText"><strong>{t.wins}</strong> galibiyet</span><span className="goldText"><strong>{t.draws}</strong> beraberlik</span><span><strong>{t.losses}</strong> mağlubiyet</span><span><strong>{t.goals}:{t.conceded}</strong> goller</span></div>}
function GoalChart({matches}:{matches:Match[]}){const rows=[...matches].reverse();const max=Math.max(1,...rows.flatMap(m=>{const c=clubMatch(m)!;return [c.goals,c.conceded]}));const x=(i:number)=>45+(i/Math.max(1,rows.length-1))*470;const y=(n:number)=>160-(n/max)*120;const points=(metric:'goals'|'conceded')=>rows.map((m,i)=>`${x(i)},${y(clubMatch(m)![metric])}`).join(' ');return <svg className="goalChart" viewBox="0 0 560 195" role="img" aria-label={`Son ${rows.length} maçın atılan ve yenilen gol grafiği. Atılan ${matchTotals(rows).goals}, yenilen ${matchTotals(rows).conceded}.`}>{[0,.5,1].map(f=><g key={f}><line x1="45" x2="515" y1={y(max*f)} y2={y(max*f)} stroke="currentColor" opacity=".12"/><text x="20" y={y(max*f)+4} fill="currentColor" fontSize="10" opacity=".5">{fixed(max*f,(max*f)%1?1:0)}</text></g>)}<polyline points={points('goals')} stroke="#dbb778" fill="none" strokeWidth="3" strokeLinejoin="round"/><polyline points={points('conceded')} stroke="#7f8797" fill="none" strokeWidth="2" strokeDasharray="5 5"/>{rows.map((m,i)=><g key={m.matchId}><circle cx={x(i)} cy={y(clubMatch(m)!.goals)} r="4" fill="#dbb778"><title>{dateOnly(m.timestamp)}: {clubMatch(m)!.goals} atılan, {clubMatch(m)!.conceded} yenilen gol</title></circle>{(i===0||i===rows.length-1||i===Math.floor(rows.length/2))&&<text x={x(i)} y="186" textAnchor="middle" fill="currentColor" opacity=".5" fontSize="10">{dateOnly(m.timestamp)}</text>}</g>)}</svg>}
function MatchDetails({match}:{match:Match}){const c=clubMatch(match)!;const [team,setTeam]=useState('79638');const rows=Object.entries(match.players?.[team]||{}).sort(([,a],[,b])=>Number(b.rating)-Number(a.rating));const opponentId=Object.keys(match.clubs).find(id=>id!=='79638')!;return <><p className="eyebrow">{stamp(match.timestamp)} · LİG MAÇI</p><div className="detailScore"><span>LEO XI</span><strong>{c.goals} : {c.conceded}</strong><span>{c.opponent.details?.name}</span></div><div className="segmented detailTeam"><button className={team==='79638'?'chosen':''} onClick={()=>setTeam('79638')}>LEO XI</button><button className={team===opponentId?'chosen':''} onClick={()=>setTeam(opponentId)}>Rakip kadro</button></div><div className="tableWrap"><table><thead><tr><th>OYUNCU</th><th>ROL</th><th>PUAN</th><th>GOL</th><th>ASİST</th><th>PAS</th><th>PAS %</th><th>MÜDAHALE</th></tr></thead><tbody>{rows.map(([id,p])=><tr key={id}><td><strong>{p.playername}</strong>{Number(p.mom)>0&&<span className="momTag">MVP</span>}</td><td>{positions[p.pos]||'—'}</td><td><span className="rating">{fixed(Number(p.rating),1)}</span></td><td>{p.goals??'—'}</td><td>{p.assists??'—'}</td><td>{p.passesmade??'—'} / {p.passattempts??'—'}</td><td>{Number(p.passattempts)>0?`${fixed(Number(p.passesmade)/Number(p.passattempts)*100,0)}%`:'—'}</td><td>{p.tacklesmade??'—'} / {p.tackleattempts??'—'}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">EA bu takımın oyuncu detaylarını döndürmedi.</p>}</div><EventAnalysis key={team} matches={[match]} teamId={team}/><p className="footnote">Pas ve müdahale: başarılı / deneme. EA maç kaydı; tam saha konumları gösterilmez.</p></>}
