'use client';
import {useMemo,useState,useSyncExternalStore} from 'react';
import type {Match} from '../lib/club-types';
import {labMetrics,labRows,pooled,outcomes,splitProfile,opponents,nearestMatches,rosterSimilarity,experimentResult,researchSource,eligible} from '../lib/team-lab';
import type {MetricKey,LabRow,Experiment} from '../lib/team-lab';
const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('tr-TR',{maximumFractionDigits:2});
const date=(t:number)=>new Date(t*1000).toLocaleString('tr-TR',{timeZone:'Europe/Amsterdam',dateStyle:'short',timeStyle:'short'});
const subscribe=(cb:()=>void)=>{window.addEventListener('storage',cb);window.addEventListener('leo-lab-save',cb);return()=>{window.removeEventListener('storage',cb);window.removeEventListener('leo-lab-save',cb)}};
function useLocal(key:string){
 const raw=useSyncExternalStore(subscribe,()=>{try{return localStorage.getItem(key)||'[]'}catch{return '[]'}},()=> '[]');
 const value=useMemo(()=>{try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[]}catch{return []}},[raw]);
 function save(next:unknown){localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event('leo-lab-save'));}
 return {value,save};
}
function download(value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='leo-xi-laboratuvar.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Games({rows,onMatch}:{rows:LabRow[];onMatch:(id:string)=>void}){return <div className="labGames">{rows.map(r=><button key={r.id} onClick={()=>onMatch(r.id)}><span>{r.opponent}<small>{date(r.time)}</small></span><strong>{r.gf} : {r.ga}</strong></button>)}{!rows.length&&<p>Bu kapsamda maç yok.</p>}</div>}
function Profile({rows}:{rows:LabRow[]}){return <div className="labProfile">{labMetrics.map(m=>{const value=pooled(rows,m.key);return <div key={m.key}><span>{m.label}</span><strong>{fmt(value)} <small>{m.unit}</small></strong><meter min={0} max={100} value={value??0} aria-label={m.label}/></div>})}</div>}
function Outcome({title,rows}:{title:string;rows:LabRow[]}){const o=outcomes(rows);return <div className="labOutcome"><h4>{title}</h4><p>{o.n} maç</p><strong>{fmt(o.points)} <small>puan / maç</small></strong><p>{fmt(o.gf)} atılan · {fmt(o.ga)} yenilen / maç</p></div>}
export default function TeamLab({matches,onMatch,rematches=false}:{matches:Match[];onMatch:(id:string)=>void;rematches?:boolean}){
 const [period,setPeriod]=useState('all');const [metric,setMetric]=useState<MetricKey>('insideShare');const [selected,setSelected]=useState('');
 const [title,setTitle]=useState('');const [target,setTarget]=useState(6);const [error,setError]=useState('');const [note,setNote]=useState('');
 const saved=useLocal('leo-xi-lab-experiments-v1');const notes=useLocal('leo-xi-rematch-notes-v1');
 const all=useMemo(()=>labRows(matches),[matches]);const rows=useMemo(()=>period==='all'?all:all.slice(0,Number(period)),[all,period]);
 const groups=useMemo(()=>opponents(rows),[rows]);const opponent=groups.find(g=>g.id===selected)||groups[0];
 const definition=labMetrics.find(m=>m.key===metric)!;const split=splitProfile(rows,metric);
 const experiments=saved.value.filter((x:Experiment)=>x&&typeof x.title==='string'&&typeof x.start==='number'&&Array.isArray(x.baselineIds)&&labMetrics.some(m=>m.key===x.metric)&&Number.isInteger(x.target)&&x.target>=3&&x.target<=20) as Experiment[];
 const exportData=()=>download({version:1,source:researchSource,experiments:experiments,notes:notes.value,rows});
 function create(){try{if(!title.trim())throw Error('Deney için kısa bir başlık yaz.');const start=Math.floor(Date.now()/1000);const base=all.filter(r=>r.time<start&&eligible(r,metric)).slice(0,target);if(base.length<3)throw Error('Deney için en az 3 geçerli geçmiş maç gerekiyor.');saved.save([...experiments,{id:crypto.randomUUID(),title:title.trim().slice(0,160),metric,start,target,baselineIds:base.map(r=>r.id),createdAt:Date.now()}]);setTitle('');setError('')}catch(e){setError((e as Error).message)}}
 function saveNote(){try{if(!opponent||!note.trim())return;notes.save([...notes.value,{id:crypto.randomUUID(),opponentId:opponent.id,text:note.trim().slice(0,1500),at:Date.now()}]);setNote('');setError('')}catch{setError('Not bu tarayıcıya kaydedilemedi.')}}
 return <section className="teamLab"><div className="pageHead"><div><p className="eyebrow">{rematches?'AYNI RAKİP, YENİ SAYFA':'OYUNUNUZU KEŞFEDİN'}</p><h2>{rematches?'Rövanş defteri':'Takım Laboratuvarı'}</h2><p className="bodyText">{rematches?'Ortak geçmiş, oyun profili ve tekrar karşılaşmalar.':'Oyun tercihleri, karşılaştırılabilir maçlar ve ölçülebilir takım deneyleri.'}</p></div></div>
 <div className="labToolbar"><label>Maç kapsamı<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Tüm kayıtlar</option><option value="5">Son 5 maç</option><option value="10">Son 10 maç</option><option value="20">Son 20 maç</option></select></label><span>{rows.length} kayıtlı maç</span><button onClick={exportData}>Verileri ve notları indir</button></div>
 {error&&<p role="alert" className="errorText">{error}</p>}
 <p className="footnote">İnsan oyuncu olaylarından hesaplanır; AI oyuncularını kapsamaz. Eksik veri sıfır değildir. Topluluk olay eşlemeleri resmî EA tanımları değildir. Gözlenen ilişkiler taktik etkisini kanıtlamaz.</p>
 {rematches?<>{!opponent?<p className="panel">Rakip geçmişi için kayıtlı maç gerekiyor.</p>:<><div className="labToolbar"><label>Rakip<select value={opponent.id} onChange={e=>{setSelected(e.target.value);setNote('')}}>{groups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.games.length} maç</option>)}</select></label><span>Kulüp ID: {opponent.id}</span></div><div className="labColumns"><section className="panel"><h3>{opponent.name}</h3><Outcome title="Karşılaşma bilançosu" rows={opponent.games}/><Games rows={opponent.games} onMatch={onMatch}/></section><section className="panel"><h3>Bu rakibe karşı bizim oyun profilimiz</h3><Profile rows={opponent.games}/><p className="footnote">Bu profil rakibin taktiği değil, LEO XI’nin bu rakiple maçlarındaki kayıtlı aksiyonlarıdır.</p></section></div>
 {opponent.games.length>1&&<section className="panel"><h3>Son karşılaşmada ne değişti?</h3><p>İnsan kadrosu benzerliği: %{fmt((rosterSimilarity(opponent.games[0],opponent.games[1])??0)*100)} · ortak oyuncu / iki kadronun birleşimi.</p><div className="tableWrap"><table><thead><tr><th>Metrik</th><th>Önceki karşılaşma</th><th>Son karşılaşma</th></tr></thead><tbody>{labMetrics.map(m=><tr key={m.key}><td>{m.label} ({m.unit})</td><td>{fmt(pooled([opponent.games[1]],m.key))}</td><td>{fmt(pooled([opponent.games[0]],m.key))}</td></tr>)}</tbody></table></div></section>}
 <section className="panel"><h3>Rakip notları</h3><p className="footnote">Senin gözlemin · yalnız bu tarayıcıda saklanır, takım arkadaşlarına gönderilmez. JSON indirerek yedekleyebilirsin.</p><label className="formLabel">Karşılaşmadan aklında kalan<textarea maxLength={1500} value={note} onChange={e=>setNote(e.target.value)} placeholder="Örn. ikinci karşılaşmada geriden çıkarken acele ettik."/></label><button className="primaryButton" disabled={!note.trim()} onClick={saveNote}>Notu kaydet</button>{notes.value.filter((n:{opponentId:string;text:string})=>n&&n.opponentId===opponent.id&&typeof n.text==='string').map((n:{id:string;text:string;at:number})=><p className="labNote" key={n.id}>{n.text}<small>{date(n.at/1000)} · kullanıcı notu</small></p>)}</section></>}</>:<>
 <section className="panel"><h3>Oyun parmak izi</h3><p className="bodyText">Tek pas, ara pas, şut tercihi ve bölgesel top dengesi aynı görünümde.</p><Profile rows={rows}/></section>
 <section className="panel"><h3>Hangi tercihlerimiz hangi sonuçlarla birlikte görülüyor?</h3><label className="formLabel">İncelenecek oyun tercihi<select value={metric} onChange={e=>setMetric(e.target.value as MetricKey)}>{labMetrics.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><p>{definition.question}</p><p className="footnote">Eşik: seçili maçların medyanı {fmt(split.median)} {definition.unit}. Eşiğe eşit {split.ties} maç karşılaştırma dışında. Eksik/az kapsamlı {split.excluded} maç dışarıda.</p><div className="labColumns"><Outcome title="Medyanın altındaki maçlar" rows={split.low}/><Outcome title="Medyanın üstündeki maçlar" rows={split.high}/></div><p className="notice">{split.enough?'Betimleyici karşılaştırma: rakip ve kadro farkları sonuçları etkileyebilir.':'Henüz iki grupta da en az 5 maç yok. Bu sayılardan taktik önerisi çıkarılmıyor.'}</p><details><summary>Karşılaştırmayı oluşturan maçlar</summary><div className="labColumns"><Games rows={split.low} onMatch={onMatch}/><Games rows={split.high} onMatch={onMatch}/></div></details></section>
 <section className="panel"><h3>Son maçın geçmişteki benzerleri</h3><p className="footnote">Şut tercihi, ileri pas, kayıp ve kazanım bölgesi oranlarında eşit ağırlıklı mutlak fark. En az üç ortak boyut; yalnız daha eski maçlar. Benzerlik bir kazanma tahmini değildir.</p>{rows[0]&&nearestMatches(rows[0],all).map(({row,distance,dimensions})=><div className="labNeighbor" key={row.id}><button onClick={()=>onMatch(row.id)}>{row.opponent} · {row.gf}:{row.ga}</button><span>Ortalama fark {fmt(distance*100)} yüzde puan · {dimensions} boyut</span></div>)}{(!rows[0]||!nearestMatches(rows[0],all).length)&&<p>Karşılaştırılabilir geçmiş maç yok.</p>}</section>
 <section className="panel"><h3>Bir sonraki maçlarda bir fikir dene</h3><p>Örneğin: “Şutları ceza sahası içine taşıyalım.” Başlangıçtaki geçmiş maçlar sabitlenir; sonraki geçerli maçlar otomatik eklenir.</p><div className="labToolbar"><label>Deney başlığı<input maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Takım olarak neyi deneyeceğiz?"/></label><label>Ölçüt<select value={metric} onChange={e=>setMetric(e.target.value as MetricKey)}>{labMetrics.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label>Hedef maç<select value={target} onChange={e=>setTarget(Number(e.target.value))}>{[3,6,10].map(n=><option key={n}>{n}</option>)}</select></label><button className="primaryButton" onClick={create}>Deneyi başlat</button></div><p className="footnote">Deney planları bu tarayıcıda saklanır. JSON indirerek yedekle. Hedef, nedensel etkiyi kanıtlamak değil karşılaştırmayı önceden tanımlamaktır.</p>
 {experiments.map(ex=>{const r=experimentResult(ex,all);return <article className="labExperiment" key={ex.id}><h4>{ex.title}</h4><p>{labMetrics.find(m=>m.key===ex.metric)?.label} · {r.complete?'Tamamlandı':'Veri birikiyor'} · {r.after.length}/{ex.target} maç</p><p>Önce: <strong>{fmt(r.before)}</strong> → Sonra: <strong>{fmt(r.current)}</strong></p><div className="labColumns"><Outcome title="Sabit geçmiş" rows={r.baseline}/><Outcome title="Deney dönemi" rows={r.after}/></div><details><summary>Kaynak maçlar</summary><Games rows={[...r.baseline,...r.after]} onMatch={onMatch}/></details></article>})}</section>
 </>}
 <details className="panel"><summary>Formüller ve veri kapsamı</summary><p>Oranlar ham pay/paydalardan havuzlanır. Sıfır payda: veri yok. Her oyuncu için şut/gol/asist eşleşmesi kontrol edilir. Medyan karşılaştırmasında en az %80 ilgili metrikte geçerli insan oyuncu kaydı aranır. Genel profiller yalnız geçerli kayıtları kapsar.</p><p>İsabet olaylarına bazı bloklanan şutlar dahil olabilir. Tek pas ve yön değiştirme farklı sayaçlardır, pasta dilimleri gibi toplanmaz.</p>{labMetrics.map(m=><p key={m.key}><strong>{m.label}:</strong> {m.formula} (event ID)</p>)}<p>{rows.reduce((s,r)=>s+r.covered,0)} / {rows.reduce((s,r)=>s+r.total,0)} geçerli olay kaydı. Payda sıfır veya kategori uyuşmazlığında ilgili metrik ayrıca dışlanır.</p><a href={researchSource} target="_blank" rel="noreferrer">EA FC API topluluk araştırması</a></details>
 </section>;
}
